### ISSUE TITLE
Updated Bio and Photo for Board and Officers

### ISSUE THREAD

**Issue by the-simian** [techlahoma/board_meetings#43]

**Comment by robolucas** [comment]
Born and raised in Oklahoma, Lucas Watson is a technology recruiter who loves PC games, sci-fi/fantasy novels, making music and building drones. He's served as a board member for Techlahoma since January of 2016 and is a co-founder of StarSpace46. Lucas attends a LOT of user groups in OKC and is committed to growing the technology community in Oklahoma.

If you need more or this isn't deep enough let me know and I can fill it out with education, how I help Techlahoma, other things about me, etc. :)

**Comment by matthewreily** [comment]
![878a0389](https://cloud.githubusercontent.com/assets/8399844/22393988/40eaa5e2-e4d9-11e6-806a-c7a3e8910d40.jpg)

Matthew loves being part of the tech community and building relationships.  He's obsessed with running and will talk your ear off about it if you give him  half a chance. He's been a Board member since January 2016 and is the newly elected secretary of Techlahoma.  He's the founding member and one of the current organizers of OKC#.  He also helps in the leadership of OKC TUG and Big Data Science in OKC user groups.

**Comment by groovecoder** [comment]
By day, Luke writes web code at Mozilla, focusing on Privacy & Security prototypes & experiments for Firefox. By night, he has helped tech communities like Tulsa Web Devs and Code for Tulsa since 2011. He owes all his best experiences to the open-source community and tries to give back. He has been a Techlahoma board member since January 2016.

**Comment by TRozzell** [comment]
Founder and CEO of Learn To Code, Tatiana spends most of her free time
promoting and teaching coding to the kids of middle and high school. Member
of Tulsa WebDevs and coding enthusiast. She joined Techlahoma board in
January 2017.

**Comment by rhoegg** [comment]
Ryan is a software consultant, part of the OKCJUG "old guard", and StarSpace46 founder. Ryan loves software, entrepreneurship, and community, and wishes he could invent Hermione's time turner and do all the great projects he's considered.

He believes we are making Oklahoma's tech scene vibrant and exciting. The community we are building can become the nation's model for how to stimulate innovation by empowering people to learn, create, and teach.

<img src="https://cloud.githubusercontent.com/assets/44559/22394223/934cdfc0-e4df-11e6-9a28-fd382186311e.jpg" width="320" />

**Comment by DevinClark** [comment]
Devin is a Front-End Developer for a private weather company in Norman, OK. He volunteers for the OKC JavaScript Group and has been a Techlahoma Board member since January 2016. In his free time, he enjoys video games and writing mediocre bios.

![devinclark](https://cloud.githubusercontent.com/assets/353563/22394789/62044056-e4ef-11e6-9d44-5e0aab1d7daf.jpeg)

**Comment by seejessicacode** [comment]
![img_0169](https://cloud.githubusercontent.com/assets/943398/22396637/f218825e-e523-11e6-997e-25127c468d4d.JPG)

An okie since birth, coder since she was a bored tween, and nag since she married into an entire family diagnosed with ADD, Jessica Campbell is a .Net dev with strong interest in JavaScript. Her background serves her well in coordinating OKC.js events, organizing Techlahoma's email inbox, and on-boarding user groups joining the Techlahoma family.
Jessica has recently leveled up from volunteer to board member and leads the user group committee.

**Comment by jagthedrummer** [comment]
![jeremygreen](https://cloud.githubusercontent.com/assets/58702/22397665/59dccf04-e53c-11e6-9987-f45b09936ffe.jpg)

Jeremy is a full-stack web engineer specializing in Ruby on Rails and Ember.js for eCommerce and SaaS applications. He's an international public speaker, the founder and developer of a couple of SaaS applications, a core team member of Code for OKC, and an organizer of the OkcRuby developer group. When not coding you might find him taking photos or brewing beer. He's been a Techlahoma board member since January of 2016.

**Comment by dustincurzon** [comment]
Dustin Curzon is the Executive Director of 36 Degrees North, Tulsa's Basecamp for Entrepreneurs. 36 Degrees North connects entrepreneurs to the workspace, community and resources needed to build successful businesses. Prior to 36 Degrees North, Dustin was the Founder and Chief Storyteller of Narrable.com, a web-based storytelling platform for capturing the stories behind important family photos. Dustin joined the Techlahoma board in 2017 to help connect the technology and entrepreneur communities. 

![dustin](https://cloud.githubusercontent.com/assets/16961799/22398019/54d4a0d8-e544-11e6-8b1f-9452865904ab.JPG)

**Comment by aestus** [comment]
Tommy Yi is an entrepreneur, designer and technology evangelist. He is the Director of UX for projekt202, an experience driven and design led software and product development company and has helped some of the world's largest brands to innovate.  He is also a co-founder of StarSpace46, Inc., which serves to be a community hub and center for entrepreneurship and technology in Oklahoma City.  Tommy helped to established the state's first co-working facilities and strives to promote Oklahoma-based innovation and tech to solve problems in our "own backyard."

![947381_10103614235365247_6661273237636831195_n](https://cloud.githubusercontent.com/assets/97417/22399299/445738fe-e55f-11e6-8cb2-577bb5ae3b33.jpg)

**Comment by the-simian** [comment]
Thank you everyone that's submitted info so far :)
